kind: Service
apiVersion: v1
metadata:
  name: ${SERVICE_NAME}
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  labels:
    app: ${SERVICE_NAME}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
      tier: backend
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
        tier: backend
    spec:
      containers:
      - name: ${SERVICE_NAME}
        image: gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
        env:
        - name: MICROSERVICE_URL
          value: http://practicaseam
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP